embedding:
  _target_: vital.results.embedding.GroupsEmbeddingPlots

  # Base ResultsProcessor options
  progress_bar: ${trainer.enable_progress_bar}
  multiprocessing: True

  # Options specific to GroupsEmbeddingPlots
  embedding_kwargs: null
  interactive: False
