default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/timothycrosley/isort
    rev: 5.1.4
    hooks:
      - id: isort
        name: isort
        args: [--settings-path, ./pyproject.toml]
        types: [python]

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        name: black
        args: [--config, ./pyproject.toml]
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8
        args: [--config, ./setup.cfg]
        types: [python]
