default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/timothycrosley/isort
    rev: "4.3.21-2"
    hooks:
      - id: isort
        name: isort
        args: [--settings-path, ./.isort.cfg]
        types: [python]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: black
        entry: python -m black
        args: [--config, ./pyproject.toml]
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.3"
    hooks:
      - id: flake8
        name: flake8
        entry: python -m flake8
        args: [--config, ./setup.cfg]
        types: [python]
