default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [--settings-path, ./pyproject.toml]
        types: [python]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        args: [--config, ./pyproject.toml]
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies: [flake8-docstrings==1.7.0]
        args: [--config, ./setup.cfg]
        types: [python]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: '.ipynb'
