# @package _global_

# NOTE: This custom launcher (separate from the built-in 'hydra/launcher' node) is meant to override global options
# that depend on the hardware resources available and for which the default options are for local runs
# (e.g. GPU devices, number of dataloader workers, progress bar display, etc.)

defaults:
  - override /hydra/launcher: alliancecan

trainer:
  enable_progress_bar: False

# Path to the root of the virtualenv to activate for the jobs
venv: ???

# Path of the data to copy from the shared filesystem to the compute node
data_dir_to_copy: ???
