image:
  _target_: vital.results.camus.image.MhdImages

  # Base ResultsProcessor options
  progress_bar: ${trainer.enable_progress_bar}
  multiprocessing: True

  # Options specific to ResultsProcessor using CAMUS results iterators
  results_path: ${hydra:run.dir}/test.h5
  use_sequence: ${data.use_sequence}

  # Options specific to MhdImages
  inputs: ["pred/raw"]
