# This is an example config to show how to use vital and hydra configs is your project.

defaults:
  - vital_default # This references default config from vital.conf
  - override /system: classification.yaml
  - override system/module: mlp.yaml
  - override /data: mnist.yaml

# Overwrite arguments from configs here:
# You can also add arguments that are not defined in the object configs.
trainer:
  max_epochs: 300

data:
  batch_size: 128

callbacks:
  early_stopping:
    patience: 10

# Set this to get configs in VITAL submodule
hydra:
  searchpath:
    - pkg://vital.config
