# This is an example config to show how to use vital and hydra configs is your project.

defaults:
  - vital_default # This entry references the default config from vital.conf
  - callbacks:
    - early_stopping
  - override system: classification
  - override system/module: mlp
  - override data: mnist
  - override logger: comet/offline

# Overwrite arguments from configs here:
# You can also add arguments that are not defined in the object configs.
trainer:
  max_epochs: 300

data:
  batch_size: 128

callbacks:
  early_stopping:
    patience: 10
