name: "Code Format"
on:
  # Trigger the workflow on push or pull request,
  # but only for the master and dev branches
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and run pre-commit hooks
        uses: pre-commit/action@v2.0.0
